#!/usr/bin/env python3
"""sync-ollama-models.py — syncs installed Ollama models into config.yaml.

Bounded to a sentinel-marked block inside the `models:` section. Idempotent.
Soft filter on tools: all models added; non-tool ones get supports_tools: false
and a `(no tools)` suffix so the frontend can dim them.

Env vars:
    OLLAMA_HOST    default '127.0.0.1:11434'

Flags:
    --config PATH  config.yaml path (default: ./config.yaml)
    --dry-run      print resulting config.yaml to stdout, don't write
    --print-only   print just the rendered Ollama block (skips config edit)
    --verbose      log Ollama API calls and per-model capabilities
"""
import argparse, json, os, re, sys, urllib.request, urllib.error
from pathlib import Path

SENTINEL_START = "# >>> sync-ollama-models START — regenerated by scripts/sync-ollama-models.py; do not edit <<<"
SENTINEL_END   = "# <<< sync-ollama-models END >>>"


def log(verbose, msg):
    if verbose:
        print(f"[sync-ollama] {msg}", file=sys.stderr)


def normalize_host(h):
    return h if h.startswith(("http://", "https://")) else f"http://{h}"


def http_json(url, body=None, timeout=10):
    headers = {"Accept": "application/json"}
    data = None
    if body is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(body).encode()
    req = urllib.request.Request(
        url, data=data, headers=headers,
        method="POST" if body else "GET",
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def get_models(base_url, verbose):
    log(verbose, f"GET {base_url}/api/tags")
    tags = http_json(f"{base_url}/api/tags")
    return [m["name"] for m in tags.get("models", [])]


def get_caps(base_url, model, verbose):
    log(verbose, f"POST {base_url}/api/show ({model})")
    show = http_json(f"{base_url}/api/show", body={"model": model})
    caps = set(show.get("capabilities") or [])
    return {
        "supports_tools":    "tools"    in caps,
        "supports_vision":   "vision"   in caps,
        "supports_thinking": "thinking" in caps,
    }


def render_entry(model, caps, base_url, list_indent="  ", field_indent="    "):
    safe = re.sub(r"[^A-Za-z0-9._-]", "-", model)
    suffix = "" if caps["supports_tools"] else " (no tools)"
    return "\n".join([
        f"{list_indent}- name: ollama-{safe}",
        f"{field_indent}display_name: \"{model} (Ollama){suffix}\"",
        f"{field_indent}use: langchain_ollama:ChatOllama",
        f"{field_indent}model: {model}",
        f"{field_indent}base_url: {base_url}",
        f"{field_indent}supports_tools: {str(caps['supports_tools']).lower()}",
        f"{field_indent}supports_vision: {str(caps['supports_vision']).lower()}",
        f"{field_indent}supports_thinking: {str(caps['supports_thinking']).lower()}",
    ])


def detect_indent(lines, sec_start, sec_end):
    """Detect the list-item indent ('-') and field indent of the models: section.

    Returns (list_indent, field_indent) as strings. Falls back to upstream's
    4-space-list / 6-space-fields style if no items are found.
    """
    for i in range(sec_start + 1, sec_end):
        ln = lines[i]
        stripped = ln.lstrip(" ")
        if stripped.startswith("- "):
            list_indent = ln[: len(ln) - len(stripped)]
            # Walk forward to find the first key under this item to learn field indent.
            for j in range(i + 1, sec_end):
                ln2 = lines[j]
                stripped2 = ln2.lstrip(" ")
                if not stripped2 or stripped2.startswith("- ") or stripped2.startswith("#"):
                    if stripped2.startswith("- "):
                        break
                    continue
                if ":" in stripped2:
                    field_indent = ln2[: len(ln2) - len(stripped2)]
                    return list_indent, field_indent
            # Item with no fields; default field indent = list indent + 2 spaces.
            return list_indent, list_indent + "  "
    # No list items found; use upstream-style defaults.
    return "  ", "    "


def find_models_section(lines):
    start = None
    for i, ln in enumerate(lines):
        if re.match(r"^models:\s*(#.*)?$", ln):
            start = i
            break
    if start is None:
        return None, None
    end = len(lines)
    for j in range(start + 1, len(lines)):
        ln = lines[j]
        if not ln.strip() or ln[0].isspace() or ln.lstrip().startswith("#"):
            continue
        if re.match(r"^[A-Za-z_][A-Za-z0-9_]*:", ln):
            end = j
            break
    return start, end


def upsert(text, block):
    lines = text.split("\n")
    sec_start, sec_end = find_models_section(lines)
    if sec_start is None:
        raise RuntimeError("config.yaml has no top-level `models:` section")

    existing_start = existing_end = None
    for i in range(sec_start, sec_end):
        if SENTINEL_START in lines[i]:
            existing_start = i
        elif SENTINEL_END in lines[i]:
            existing_end = i
            break

    new_block_lines = [f"  {SENTINEL_START}", block, f"  {SENTINEL_END}"]

    if existing_start is not None and existing_end is not None:
        out = lines[:existing_start] + new_block_lines + lines[existing_end + 1:]
    else:
        insert = sec_end
        while insert > sec_start + 1 and lines[insert - 1].strip() == "":
            insert -= 1
        out = lines[:insert] + ["", *new_block_lines, ""] + lines[insert:]

    return "\n".join(out)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", default="config.yaml")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--print-only", action="store_true")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    base_url = normalize_host(os.environ.get("OLLAMA_HOST", "127.0.0.1:11434"))
    cfg_path = Path(args.config)

    try:
        models = get_models(base_url, args.verbose)
    except (urllib.error.URLError, urllib.error.HTTPError, OSError) as e:
        log(True, f"cannot reach Ollama at {base_url}: {e} — skipping")
        return 0

    entries = []
    for m in sorted(models):
        try:
            caps = get_caps(base_url, m, args.verbose)
        except Exception as e:
            log(True, f"skipping {m}: {e}")
            continue
        entries.append(render_entry(m, caps, base_url))
        log(args.verbose,
            f"  {m}: tools={caps['supports_tools']} vision={caps['supports_vision']} thinking={caps['supports_thinking']}")

    block = "\n\n".join(entries) if entries else "  # (no Ollama models installed)"

    if args.print_only:
        print(block)
        return 0

    if not cfg_path.exists():
        log(True, f"config not found: {cfg_path} — run `make config` first; skipping")
        return 0

    text = cfg_path.read_text()
    # Detect indent style from the existing models: section so our entries match.
    lines = text.split("\n")
    sec_start, sec_end = find_models_section(lines)
    if sec_start is not None:
        list_indent, field_indent = detect_indent(lines, sec_start, sec_end)
        # Re-render entries with detected indent.
        rerendered = []
        for m in sorted(models):
            try:
                caps = get_caps(base_url, m, args.verbose)
            except Exception:
                continue
            rerendered.append(render_entry(m, caps, base_url, list_indent, field_indent))
        block = "\n\n".join(rerendered) if rerendered else f"{list_indent}# (no Ollama models installed)"
    new_text = upsert(text, block)

    if new_text == text:
        log(True, "config.yaml unchanged")
        return 0

    if args.dry_run:
        print(new_text)
    else:
        cfg_path.write_text(new_text)
        log(True, f"updated {cfg_path} ({len(entries)} Ollama models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
